INSERT INTO flight (flight_number, origin_location, destination_location, flight_type, terminal_gate, arrival_time, departure_time, status, is_delayed) VALUES
    ('Beoing7371', 'Vancouver', 'Toronto', 'INBOUND', 'Gate1', NOW(), DATE_ADD(NOW(), INTERVAL 1 HOUR), 'SCHEDULED', false),
    ('Beoing7372', 'Calgary', 'Vancouver', 'INBOUND', 'Gate2', NOW(), DATE_ADD(NOW(), INTERVAL 2 HOUR), 'SCHEDULED', false),
    ('Beoing7373', 'Vancouver', 'Los Angeles', 'INBOUND', 'Gate3', NOW(), DATE_ADD(NOW(), INTERVAL 3 HOUR), 'SCHEDULED', false),
    ('Beoing7374', 'New York', 'Vancouver', 'INBOUND', 'Gate4', NOW(), DATE_ADD(NOW(), INTERVAL 4 HOUR), 'SCHEDULED', false),
    ('Beoing7375', 'Vancouver', 'London', 'INBOUND', 'Gate5', NOW(), DATE_ADD(NOW(), INTERVAL 5 HOUR), 'SCHEDULED', false),
    ('Beoing7376', 'Vancouver', 'Sydney', 'INBOUND', 'Gate6', NOW(), DATE_ADD(NOW(), INTERVAL 6 HOUR), 'SCHEDULED', false),
    ('Beoing7377', 'Vancouver', 'Mexico City', 'INBOUND', 'Gate7', NOW(), DATE_ADD(NOW(), INTERVAL 7 HOUR), 'SCHEDULED', false),
    ('Beoing7378', 'Tokyo', 'Vancouver', 'INBOUND', 'Gate8', NOW(), DATE_ADD(NOW(), INTERVAL 8 HOUR), 'SCHEDULED', false),
    ('Beoing7379', 'Vancouver', 'Chicago', 'INBOUND', 'Gate9', NOW(), DATE_ADD(NOW(), INTERVAL 9 HOUR), 'SCHEDULED', false),
    ('Beoing73710', 'Montreal', 'Vancouver', 'INBOUND', 'Gate10', NOW(), DATE_ADD(NOW(), INTERVAL 10 HOUR), 'SCHEDULED', false),
    ('Beoing73711', 'Vancouver', 'Paris', 'INBOUND', 'Gate11', NOW(), DATE_ADD(NOW(), INTERVAL 11 HOUR), 'SCHEDULED', false),
    ('Beoing73712', 'Vancouver', 'Hong Kong', 'INBOUND', 'Gate12', NOW(), DATE_ADD(NOW(), INTERVAL 12 HOUR), 'SCHEDULED', false),
    ('Beoing73713', 'London', 'Vancouver', 'INBOUND', 'Gate13', NOW(), DATE_ADD(NOW(), INTERVAL 13 HOUR), 'SCHEDULED', false),
    ('Beoing73714', 'Vancouver', 'Miami', 'INBOUND', 'Gate14', NOW(), DATE_ADD(NOW(), INTERVAL 14 HOUR), 'SCHEDULED', false),
    ('Beoing73715', 'Vancouver', 'Seattle', 'INBOUND', 'Gate15', NOW(), DATE_ADD(NOW(), INTERVAL 15 HOUR), 'SCHEDULED', false),
    ('Beoing73716', 'Los Angeles', 'Vancouver', 'INBOUND', 'Gate16', NOW(), DATE_ADD(NOW(), INTERVAL 16 HOUR), 'SCHEDULED', false),
    ('Beoing73717', 'Vancouver', 'Tokyo', 'INBOUND', 'Gate17', NOW(), DATE_ADD(NOW(), INTERVAL 17 HOUR), 'SCHEDULED', false),
    ('Beoing73718', 'Chicago', 'Vancouver', 'INBOUND', 'Gate18', NOW(), DATE_ADD(NOW(), INTERVAL 18 HOUR), 'SCHEDULED', false),
    ('Beoing73719', 'Vancouver', 'Mexico City', 'INBOUND', 'Gate19', NOW(), DATE_ADD(NOW(), INTERVAL 19 HOUR), 'SCHEDULED', false),
    ('Beoing73720', 'Sydney', 'Vancouver', 'INBOUND', 'Gate20', NOW(), DATE_ADD(NOW(), INTERVAL 20 HOUR), 'SCHEDULED', false);
